POST http://localhost:8080/events/1/register
# Authorization: Bearer <your_jwt_token>
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzg2ODg3NTA5LCJ1c2VySWQiOjF9.JnV4UmmEDvLlpE16WkXi7NUQ1xXNV5EhKlZgZQ9QEV8
